services:
  fuseki:
    image: semapps/jena-fuseki-webacl
    container_name: fuseki
    restart: always
    volumes:
      - ./data/fuseki:/fuseki
    ports:
      - "3030:3030"
    expose:
      - "3030"
    env_file: "test.env"
    networks:
      triplestore:
        ipv4_address: 172.28.5.0
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:3030 || exit 1"]
  #     interval: 5s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 1s
  # test-client:
  #   build:
  #     context: ./test/semapps
  #     dockerfile: Dockerfile
  #   depends_on:
  #     fuseki:
  #       condition: service_healthy
  #       restart: true

networks:
  triplestore:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.5.0/24
          gateway: 172.28.5.254
